site_name: ESP Coaching Frameworks

theme:
  name: material
nav:
  - Home: index.md
  - Protocols:
      - Training:
          - Torque Capacity: protocols/training/torque.md
      - (Template): protocols/training/_esp-protocol-template.md
